/**
 * Do not edit this file manually all the routes are registerd in the routes 
 * file in this directory
 */
import Vue from "vue";
import Router from "vue-router";
import Meta from 'vue-meta'
import routes from './routes'
import store from '../vuex/store'

Vue.use(Meta)

Vue.use(Router);

const router = new Router({
    mode: 'hash',
    routes
});

/**
 * Do something before every route navigation
 * This would be a good place to set the application 
 * to a loading state
 */
router.beforeEach((to, from, next) => {
    store.state.loading = true
    return next(true)
})

/**
 * Do something after every root.
 * This might be a good place to 
 * stop the loader
 */
router.afterEach((to, from) => {
    store.state.loading = false
    return true
})

export default router